"""Fetch G-Dev's pretraining corpus, one source at a time, into text files.

Every source is permissively licensed or public: nothing from a gated dataset,
nothing under GPL, LGPL or MPL. Documents are separated by a line holding only
DOC_SEP, the format pack_data.py reads. Resumable: finished shards are recorded
next to the output and skipped on a rerun.

  html    common-pile/stackv2_html_filtered  (Blue Oak licenses only)
  md      common-pile/stackv2_edu_filtered   (Markdown: docs and READMEs)
  code    codeparrot/github-code-clean       (JavaScript, TypeScript, CSS, Python),
          one pass over randomly ordered shards feeding one file per language
          group, license column filtered. Measured on three shards: each holds the
          same mix (about 100 MB JavaScript, 63 Python, 30 TypeScript, 27 CSS of
          ~357 MB), so TypeScript sets how many shards are needed.
  prose   HuggingFaceFW/fineweb-edu          (ODC-By)

The raw common-pile/stackv2 was probed and rejected: its shards hold C, C++,
C#, CSV, Jupyter and CSS, and none of Python, TypeScript or SCSS turned up.

Usage:
    python data/fetch_corpus.py html --out /tmp/gdev/corpus_html.txt --max-chars 1.8e9
    python data/fetch_corpus.py code --out /tmp/gdev/x --groups 'js:JavaScript:3.2e9;ts:TypeScript:2.2e9'
"""

import argparse
import gzip
import hashlib
import io
import json
import os
import random
import re
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

DOC_SEP = "<|doc|>"
HF = "https://huggingface.co/datasets"
PERMISSIVE = {"mit", "apache-2.0", "bsd-2-clause", "bsd-3-clause", "isc", "unlicense",
              "cc0-1.0", "0bsd", "zlib", "bsl-1.0"}
HTML_SHARDS = [f"{HF}/common-pile/stackv2_html_filtered/resolve/main/stackv2_html-{i:04d}.json.gz"
               for i in range(5)]
MD_SHARDS = [f"{HF}/common-pile/stackv2_edu_filtered/resolve/main/stack-edu-{i:04d}.json.gz"
             for i in range(4)]
CODE_SHARD = f"{HF}/codeparrot/github-code-clean/resolve/main/data/train-{{i:05d}}-of-00880.parquet"
CODE_SHARDS = 880

BAD_PATH = re.compile(r"(node_modules|bower_components|/vendor/|/vendors/|/dist/|/build/|"
                      r"\.min\.|bundle|/lib/jquery|/polyfill|/assets/js/plugins|"
                      r"-min\.|/coverage/|/docs?/api/|package-lock|yarn\.lock)", re.I)


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def headers():
    h = {"User-Agent": "g-dev-prep"}
    if os.environ.get("HF_TOKEN"):
        h["Authorization"] = f"Bearer {os.environ['HF_TOKEN']}"
    return h


def keep_code(code: str, path: str, max_chars: int = 100_000) -> bool:
    if BAD_PATH.search(path or ""):
        return False
    n = len(code)
    if n < 150 or n > max_chars:
        return False
    lines = code.split("\n")
    if max(len(l) for l in lines) > 500 or n / len(lines) > 100:
        return False
    if sum(c.isalnum() for c in code[:4000]) / min(n, 4000) < 0.25:
        return False
    head = code[:600].lower()
    if "auto-generated" in head or "autogenerated" in head or "do not edit" in head \
            or "generated by" in head:
        return False
    if code.count("base64,") > 3:
        return False
    return True


class Sink:
    """Writes kept documents, deduplicating on whitespace-insensitive content."""

    def __init__(self, out: Path, max_chars: float, code: bool = True):
        self.out, self.max_chars, self.code = out, max_chars, code
        self.done_file = Path(f"{out}.done")
        self.done = set(self.done_file.read_text().split()) if self.done_file.exists() else set()
        self.seen: set[bytes] = set()
        self.chars = out.stat().st_size if out.exists() else 0
        self.f = open(out, "a", encoding="utf-8")
        self.kept = self.dupes = 0

    def full(self):
        return self.chars >= self.max_chars

    def add(self, text: str, name: str = "") -> bool:
        if not text:
            return False
        h = hashlib.md5(re.sub(r"\s+", "", text).encode("utf-8", "ignore")).digest()
        if h in self.seen:
            self.dupes += 1
            return False
        self.seen.add(h)
        text = text.replace("<|", "< |")
        doc = f"<|file|>{os.path.basename(name)}\n{text}" if self.code and name else text
        self.f.write(doc.strip("\n") + f"\n{DOC_SEP}\n")
        self.chars += len(doc)
        self.kept += 1
        return True

    def mark_done(self, key: str):
        self.f.flush()
        self.done.add(key)
        self.done_file.write_text("\n".join(sorted(self.done)))

    def close(self):
        self.f.close()


def open_stream(url: str):
    for attempt in range(6):
        try:
            r = urllib.request.urlopen(urllib.request.Request(url, headers=headers()), timeout=120)
            return gzip.GzipFile(fileobj=r)
        except Exception as e:
            log(f"retry {attempt+1} {url[-40:]}: {e}")
            time.sleep(10 * (attempt + 1))
    raise SystemExit(f"cannot open {url}")


def run_json_shards(urls, sink, accept):
    for url in urls:
        key = url.rsplit("/", 1)[-1]
        if key in sink.done or sink.full():
            continue
        for _ in range(4):
            try:
                with io.TextIOWrapper(open_stream(url), encoding="utf-8", errors="ignore") as g:
                    for line in g:
                        if sink.full():
                            break
                        try:
                            d = json.loads(line)
                        except ValueError:
                            continue
                        m = d.get("metadata", {})
                        path = m.get("path") or m.get("filename") or ""
                        if accept(d["text"], path):
                            sink.add(d["text"], path)
                break
            except Exception as e:
                log(f"stream broke: {e}")
        sink.mark_done(key)
        log(f"  {key}: kept {sink.kept:,} dupes {sink.dupes:,} total {sink.chars/1e9:.2f}G chars")


def fetch_html(a, sink):
    run_json_shards(HTML_SHARDS, sink, lambda t, p: keep_code(t, p))


def fetch_md(a, sink):
    sink.code = False
    run_json_shards(MD_SHARDS, sink, lambda t, p: 400 <= len(t) <= 60_000)


def download(url: str, path: Path):
    for attempt in range(5):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=headers()), timeout=120) as r, \
                    open(f"{path}.part", "wb") as f:
                while chunk := r.read(1 << 22):
                    f.write(chunk)
            os.replace(f"{path}.part", path)
            return True
        except Exception as e:
            log(f"retry {attempt+1} {path.name}: {e}")
            time.sleep(10 * (attempt + 1))
    return False


def fetch_code(a):
    """One pass over github-code-clean feeding several per-language sinks. The
    next shard downloads while the current one is filtered."""
    import pyarrow.parquet as pq
    outdir = a.out.parent
    outdir.mkdir(parents=True, exist_ok=True)
    groups = {}
    for spec in a.groups.split(";"):
        name, langs, chars = spec.split(":")
        groups[name] = (set(langs.split(",")), Sink(outdir / f"corpus_{name}.txt", float(chars)))
    lang_to = {l: s for langs, s in groups.values() for l in langs}
    done_file = outdir / "code.done"
    done = set(done_file.read_text().split()) if done_file.exists() else set()
    order = list(range(CODE_SHARDS))
    random.Random(7).shuffle(order)
    order = [i for i in order if f"{i:05d}" not in done]
    raw = outdir / "raw_code"
    raw.mkdir(exist_ok=True)

    def path_of(i):
        return raw / f"{i:05d}.parquet"

    def fetch(i):
        return i, download(CODE_SHARD.format(i=i), path_of(i))

    with ThreadPoolExecutor(2) as pool:
        pending = [pool.submit(fetch, i) for i in order[:2]]
        nxt = 2
        while pending:
            if all(s.full() for _, s in groups.values()):
                break
            i, ok = pending.pop(0).result()
            if nxt < len(order):
                pending.append(pool.submit(fetch, order[nxt]))
                nxt += 1
            if not ok:
                continue
            pf = pq.ParquetFile(path_of(i))
            for batch in pf.iter_batches(columns=["code", "path", "language", "license"], batch_size=2048):
                cols = [batch.column(c).to_pylist() for c in range(4)]
                for code, p, lang, lic in zip(*cols):
                    sink = lang_to.get(lang)
                    if sink is None or sink.full() or lic not in PERMISSIVE or not code:
                        continue
                    if keep_code(code, p or ""):
                        sink.add(code, p or "")
            path_of(i).unlink()
            done.add(f"{i:05d}")
            done_file.write_text("\n".join(sorted(done)))
            for _, s in groups.values():
                s.f.flush()
            log(f"  shard {i:05d}: " + ", ".join(f"{n} {s.chars/1e9:.2f}G" for n, (_, s) in groups.items()))
    for _, s in groups.values():
        s.close()


def fetch_prose(a, sink):
    sink.code = False
    from datasets import load_dataset
    ds = load_dataset("HuggingFaceFW/fineweb-edu", "sample-10BT", split="train", streaming=True)
    for row in ds:
        if sink.full():
            break
        t = row["text"].strip()
        if len(t) >= 300:
            sink.add(t)
    sink.mark_done("fineweb-edu")


SOURCES = {"html": fetch_html, "md": fetch_md, "prose": fetch_prose}

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("source", choices=list(SOURCES) + ["code"])
    ap.add_argument("--out", type=Path, required=True, help="for code: any file in the output dir")
    ap.add_argument("--max-chars", type=float, default=0)
    ap.add_argument("--groups", default="", help="code: name:Lang1,Lang2:chars;name2:...")
    a = ap.parse_args()
    if a.source == "code":
        fetch_code(a)
        log("code: finished")
    else:
        sink = Sink(a.out, a.max_chars)
        log(f"{a.source}: target {a.max_chars/1e9:.2f}G chars, already {sink.chars/1e9:.2f}G")
        SOURCES[a.source](a, sink)
        sink.close()
        log(f"{a.source}: finished at {sink.chars/1e9:.2f}G chars")
