"""Fetch G-Dev's pretraining corpus, one source at a time, into text files.

Every source is permissively licensed or public: nothing from a gated dataset,
nothing under GPL. Each source writes documents separated by a line holding
only DOC_SEP, the format pack_data.py reads. Resumable: finished shards are
recorded in <out>.done and skipped on a rerun.

  html    common-pile/stackv2_html_filtered  (Blue Oak licenses only)
  js      codeparrot/github-code-clean JavaScript, license column filtered
  stack   common-pile/stackv2 raw shards, language filtered (CSS, TypeScript,
          Python, SVG, ...), shards picked from data/shardmap.json
  md      common-pile/stackv2_edu_filtered Markdown (docs and READMEs)
  prose   HuggingFaceFW/fineweb-edu (ODC-By)

Usage:
    python data/fetch_corpus.py html --out /kaggle/working/corpus_html.txt --max-chars 1.6e9
    python data/fetch_corpus.py stack --out /tmp/x/stack --groups 'css:CSS,SCSS:1e9;ts:TypeScript,TSX:2e9'
"""

import argparse
import gzip
import hashlib
import io
import json
import os
import random
import re
import sys
import time
import urllib.request
from pathlib import Path

DOC_SEP = "<|doc|>"
HF = "https://huggingface.co/datasets"
PERMISSIVE = {"mit", "apache-2.0", "bsd-2-clause", "bsd-3-clause", "isc", "unlicense",
              "cc0-1.0", "0bsd", "zlib", "bsl-1.0"}
HTML_SHARDS = [f"{HF}/common-pile/stackv2_html_filtered/resolve/main/stackv2_html-{i:04d}.json.gz"
               for i in range(5)]
MD_SHARDS = [f"{HF}/common-pile/stackv2_edu_filtered/resolve/main/stack-edu-{i:04d}.json.gz"
             for i in range(4)]
STACK_SHARD = HF + "/common-pile/stackv2/resolve/main/documents/{i:05d}_stackv2.jsonl.gz"
GITHUB_CODE_PARQUET = "https://huggingface.co/api/datasets/codeparrot/github-code-clean/parquet/{cfg}/train/{i}.parquet"

BAD_PATH = re.compile(r"(node_modules|bower_components|/vendor/|/vendors/|/dist/|/build/|"
                      r"\.min\.|bundle|/lib/jquery|/polyfill|/assets/js/plugins|"
                      r"-min\.|/coverage/|/docs?/api/|package-lock|yarn\.lock)", re.I)


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def headers():
    h = {"User-Agent": "g-dev-prep"}
    if os.environ.get("HF_TOKEN"):
        h["Authorization"] = f"Bearer {os.environ['HF_TOKEN']}"
    return h


def keep_code(code: str, path: str, max_chars: int = 100_000) -> bool:
    if BAD_PATH.search(path or ""):
        return False
    n = len(code)
    if n < 150 or n > max_chars:
        return False
    lines = code.split("\n")
    if max(len(l) for l in lines) > 500 or n / len(lines) > 100:
        return False
    if sum(c.isalnum() for c in code[:4000]) / min(n, 4000) < 0.25:
        return False
    head = code[:600].lower()
    if "auto-generated" in head or "autogenerated" in head or "do not edit" in head \
            or "generated by" in head:
        return False
    if code.count("base64,") > 3:
        return False
    return True


class Sink:
    """Writes kept documents, deduplicating on whitespace-insensitive content."""

    def __init__(self, out: Path, max_chars: float, code: bool = True):
        self.out, self.max_chars, self.code = out, max_chars, code
        self.done_file = Path(f"{out}.done")
        self.done = set(self.done_file.read_text().split()) if self.done_file.exists() else set()
        self.seen: set[bytes] = set()
        self.chars = out.stat().st_size if out.exists() else 0
        self.f = open(out, "a", encoding="utf-8")
        self.kept = self.dupes = 0

    def full(self):
        return self.chars >= self.max_chars

    def add(self, text: str, name: str = "") -> bool:
        if not text:
            return False
        h = hashlib.md5(re.sub(r"\s+", "", text).encode("utf-8", "ignore")).digest()
        if h in self.seen:
            self.dupes += 1
            return False
        self.seen.add(h)
        text = text.replace("<|", "< |")
        doc = f"<|file|>{os.path.basename(name)}\n{text}" if self.code and name else text
        self.f.write(doc.strip("\n") + f"\n{DOC_SEP}\n")
        self.chars += len(doc)
        self.kept += 1
        return True

    def finish_shard(self, key: str):
        self.f.flush()
        self.done.add(key)
        self.done_file.write_text("\n".join(sorted(self.done)))
        log(f"  {key}: kept {self.kept:,} dupes {self.dupes:,} total {self.chars/1e9:.2f}G chars")

    def close(self):
        self.f.close()


def open_stream(url: str):
    for attempt in range(6):
        try:
            r = urllib.request.urlopen(urllib.request.Request(url, headers=headers()), timeout=120)
            return gzip.GzipFile(fileobj=r)
        except Exception as e:
            log(f"retry {attempt+1} {url[-40:]}: {e}")
            time.sleep(10 * (attempt + 1))
    raise SystemExit(f"cannot open {url}")


def read_jsonl_shard(url, sink, accept, langs=None):
    """Stream one json(l).gz shard into the sink. Returns False if the stream died
    mid-way, in which case the caller retries the shard; dedup state makes the
    repeated head of the shard harmless."""
    try:
        with io.TextIOWrapper(open_stream(url), encoding="utf-8", errors="ignore") as g:
            for line in g:
                if sink.full():
                    break
                try:
                    d = json.loads(line)
                except ValueError:
                    continue
                m = d.get("metadata", {})
                if langs and m.get("language") not in langs:
                    continue
                text = d["text"]
                path = m.get("path") or m.get("filename") or ""
                if accept(text, path):
                    sink.add(text, path)
        return True
    except Exception as e:
        log(f"stream broke: {e}")
        return False


def run_shards(urls, sink, accept, langs=None):
    for url in urls:
        key = url.rsplit("/", 1)[-1]
        if key in sink.done:
            continue
        if sink.full():
            break
        for _ in range(4):
            if read_jsonl_shard(url, sink, accept, langs):
                break
        sink.finish_shard(key)


def fetch_html(a, sink):
    run_shards(HTML_SHARDS, sink, lambda t, p: keep_code(t, p))


def fetch_md(a, sink):
    sink.code = False
    run_shards(MD_SHARDS, sink, lambda t, p: 400 <= len(t) <= 60_000)


def fetch_stack(a):
    """One pass over the raw shards feeding several per-group sinks, so that
    CSS, TypeScript, Python and the rest share a single download instead of
    each streaming the same 2 GB shards."""
    outdir = a.out.parent
    groups = {}
    for spec in a.groups.split(";"):
        name, langs, chars = spec.split(":")
        groups[name] = (set(langs.split(",")), Sink(outdir / f"corpus_{name}.txt", float(chars)))
    wanted = set().union(*(l for l, _ in groups.values()))
    lang_to = {}
    for name, (langs, sink) in groups.items():
        for l in langs:
            lang_to[l] = sink
    smap = json.load(open(Path(__file__).with_name("shardmap.json")))
    scored = []
    for i, d in smap.items():
        total = sum(d.values()) or 1
        share = sum(v for k, v in d.items() if k in wanted) / total
        if share > 0.05:
            scored.append((share, int(i)))
    scored.sort(reverse=True)
    done_file = outdir / "stack.done"
    done = set(done_file.read_text().split()) if done_file.exists() else set()
    log(f"{len(scored)} candidate shards for {sorted(wanted)}")
    for _, i in scored:
        if all(s.full() for _, s in groups.values()):
            break
        key = f"{i:05d}"
        if key in done:
            continue
        url = STACK_SHARD.format(i=i)
        for _ in range(4):
            try:
                with io.TextIOWrapper(open_stream(url), encoding="utf-8", errors="ignore") as g:
                    for line in g:
                        try:
                            d = json.loads(line)
                        except ValueError:
                            continue
                        m = d.get("metadata", {})
                        sink = lang_to.get(m.get("language"))
                        if sink is None or sink.full():
                            continue
                        path = m.get("path") or m.get("filename") or ""
                        if keep_code(d["text"], path):
                            sink.add(d["text"], path)
                break
            except Exception as e:
                log(f"stream broke: {e}")
        done.add(key)
        done_file.write_text("\n".join(sorted(done)))
        log(f"  shard {key}: " + ", ".join(f"{n} {s.chars/1e9:.2f}G" for n, (_, s) in groups.items()))
    for _, s in groups.values():
        s.close()


def fetch_js(a, sink):
    import pyarrow.parquet as pq
    raw = sink.out.parent / "raw_js"
    raw.mkdir(exist_ok=True)
    for i in range(a.parquet_shards):
        key = f"JavaScript-all-{i}"
        if key in sink.done or sink.full():
            continue
        path = raw / f"{key}.parquet"
        if not path.exists() or path.stat().st_size < 1_000_000:
            for attempt in range(5):
                try:
                    url = GITHUB_CODE_PARQUET.format(cfg="JavaScript-all", i=i)
                    with urllib.request.urlopen(urllib.request.Request(url, headers=headers()), timeout=120) as r, \
                            open(f"{path}.part", "wb") as f:
                        while chunk := r.read(1 << 22):
                            f.write(chunk)
                    os.replace(f"{path}.part", path)
                    break
                except Exception as e:
                    log(f"retry {attempt+1} {key}: {e}")
                    time.sleep(10 * (attempt + 1))
            else:
                break
        pf = pq.ParquetFile(path)
        for batch in pf.iter_batches(columns=["code", "path", "license"], batch_size=4096):
            for code, p, lic in zip(*(batch.column(c).to_pylist() for c in range(3))):
                if lic in PERMISSIVE and code and keep_code(code, p or ""):
                    sink.add(code, p or "file.js")
        path.unlink()
        sink.finish_shard(key)


def fetch_prose(a, sink):
    sink.code = False
    from datasets import load_dataset
    ds = load_dataset("HuggingFaceFW/fineweb-edu", "sample-10BT", split="train", streaming=True)
    for row in ds:
        if sink.full():
            break
        t = row["text"].strip()
        if len(t) >= 300:
            sink.add(t)
    sink.finish_shard("fineweb-edu")


SOURCES = {"html": fetch_html, "md": fetch_md, "js": fetch_js, "prose": fetch_prose}

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("source", choices=list(SOURCES) + ["stack"])
    ap.add_argument("--out", type=Path, required=True, help="for stack: any file in the output dir")
    ap.add_argument("--max-chars", type=float, default=0)
    ap.add_argument("--groups", default="", help="stack: name:Lang1,Lang2:chars;name2:...")
    ap.add_argument("--parquet-shards", type=int, default=12)
    a = ap.parse_args()
    if a.source == "stack":
        fetch_stack(a)
        log("stack: finished")
    else:
        sink = Sink(a.out, a.max_chars)
        log(f"{a.source}: target {a.max_chars/1e9:.2f}G chars, already {sink.chars/1e9:.2f}G")
        SOURCES[a.source](a, sink)
        sink.close()
        log(f"{a.source}: finished at {sink.chars/1e9:.2f}G chars")
